export async function downloadBill(b:any){
const {jsPDF}=await import('jspdf');
const doc=new jsPDF({unit:'mm',format:'a5',compress:true,putOnlyUsedFonts:true});
for(const [file,style] of [['DejaVuSans.ttf','normal'],['DejaVuSans-Bold.ttf','bold']]){const r=await fetch(import.meta.env.BASE_URL+'fonts/'+file);if(!r.ok)throw new Error('Bill font unavailable');const bytes=new Uint8Array(await r.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));doc.addFileToVFS(file,btoa(binary));doc.addFont(file,'CraftSans',style)}doc.setFont('CraftSans','normal');const w=148,margin=14;let y=16;const green:[number,number,number]=[139,9,162],muted:[number,number,number]=[139,9,162];
const text=(s:string,x:number,yy:number,size=10,color=green,align:any='left')=>{doc.setFontSize(size);doc.setTextColor(...color);doc.text(s,x,yy,{align})};
doc.setDrawColor(139,9,162);doc.setFillColor(139,9,162);doc.roundedRect(w/2-11,y,22,22,4,4,'F');doc.setFont('CraftSans','bold');text('JC',w/2,y+15,20,[255,255,255],'center');y+=32;
doc.setFont('CraftSans','bold');const title=doc.splitTextToSize(b.shop.name,120);text(title,w/2,y,19,green,'center');y+=title.length*7;doc.setFont('CraftSans','normal');text('JUICES  /  SHAKES  /  ICE POPS',w/2,y,7,muted,'center');y+=7;
for(const line of [b.shop.address,b.shop.phone].filter(Boolean)){const ls=doc.splitTextToSize(line,115);text(ls,w/2,y,9,muted,'center');y+=ls.length*4.5}
y+=6;doc.setDrawColor(139,9,162);doc.line(margin,y,w-margin,y);y+=8;doc.setFont('CraftSans','bold');text('JC-'+String(b.number).padStart(6,'0'),margin,y,10);doc.setFont('CraftSans','normal');text(new Date(b.date+'T12:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}),w-margin,y,9,muted,'right');y+=8;
if(b.status==='cancelled'){text('CANCELLED',margin,y,12,[139,9,162]);y+=8}
function header(){doc.setFillColor(255,255,255);doc.roundedRect(margin,y-5,w-margin*2,9,1,1,'F');doc.setFont('CraftSans','bold');text('ITEM',margin+3,y,8);text('QTY',102,y,8,green,'right');text('AMOUNT',w-margin-3,y,8,green,'right');doc.setFont('CraftSans','normal');y+=10}header();
for(const l of b.lines){const name=doc.splitTextToSize(l.name,66);const h=name.length*4.5+10;if(y+h>180){doc.addPage();y=18;header()}text(name,margin+2,y,10);text(String(l.qty),102,y,10,green,'right');text((l.price*l.qty/100).toFixed(2),w-margin-3,y,10,green,'right');y+=name.length*4.5;const desc=doc.splitTextToSize((l.brand?l.brand+' / ':'')+'₹ '+(l.price/100).toFixed(2)+' each',70);text(desc,margin+2,y,8,muted);y+=desc.length*4+5;doc.setDrawColor(139,9,162);doc.line(margin,y-3,w-margin,y-3)}
if(y+40>198){doc.addPage();y=20}y+=4;doc.setFillColor(...green);doc.roundedRect(margin,y-5,w-margin*2,17,2,2,'F');doc.setFont('CraftSans','bold');text(b.status==='cancelled'?'CANCELLED TOTAL':'TOTAL PAID',margin+5,y+5,9,[255,255,255]);text('₹ '+(b.total/100).toFixed(2),w-margin-5,y+5,17,[255,255,255],'right');y+=22;doc.setFont('CraftSans','normal');text('Payment: '+b.payment,margin,y,9,muted);y+=12;const footer=doc.splitTextToSize(b.shop.footer,115);text(footer,w/2,y,9,green,'center');const pages=doc.getNumberOfPages();for(let p=1;p<=pages;p++){doc.setPage(p);text('JUICE CRAFT  /  '+p+' of '+pages,w/2,202,7,muted,'center')}doc.save('JUICE-CRAFT-JC-'+String(b.number).padStart(6,'0')+'.pdf');}
