import {db,sql,all,one,today,now,string,qty,cents,date,eventDate,digest,password,verify,cookie,authenticated,response,login,getReport,shopSettings} from './server.ts';

export async function GET(req:Request){try{if(!await authenticated(req))return response({error:'Please sign in.'},401);const u=new URL(req.url),action=u.searchParams.get('action')??'bootstrap';if(action==='bootstrap'){const a=await one('SELECT changed FROM admin WHERE id=1');return response({products:await all('SELECT p.*,c.name category_name,b.name brand_name FROM products p LEFT JOIN masters c ON c.id=p.category LEFT JOIN masters b ON b.id=p.brand ORDER BY p.name'),masters:await all('SELECT * FROM masters ORDER BY name'),settings:await shopSettings(),mustChange:!a?.changed,today:today()})}if(action==='dashboard'){
 const end=today(),range=u.searchParams.get('range')??'7';if(!['7','30','90','all'].includes(range))return response({error:'Invalid report period.'},400);
 const start=new Date(end+'T12:00:00Z');start.setUTCDate(start.getUTCDate()-(range==='all'?6:Number(range)-1));let from=start.toISOString().slice(0,10);
 if(range==='all'){const first=await one("SELECT MIN(date) date FROM (SELECT date FROM sales UNION ALL SELECT date FROM movements UNION ALL SELECT date FROM expenses) dates");if(first?.date&&first.date<from)from=first.date;}
 const monthly=(new Date(end).getTime()-new Date(from).getTime())/86400000>90;
 const group=monthly?'substr(date,1,7)':'date';
 const days=await all(`SELECT ${group} date,SUM(total) revenue,SUM(packaged-cost) margin,COUNT(*) bills FROM sales WHERE date BETWEEN ? AND ? AND status='completed' GROUP BY ${group}`,from,end);
 const losses=await all(`SELECT ${group} date,SUM(-qty*cost) total FROM movements WHERE date BETWEEN ? AND ? AND type IN ('wastage','adjustment') AND qty<0 GROUP BY ${group}`,from,end);
 const expenses=await all(`SELECT ${group} date,SUM(amount) total FROM expenses WHERE date BETWEEN ? AND ? GROUP BY ${group}`,from,end);
 const dm=new Map(days.map((d:any)=>[d.date,d])),lm=new Map(losses.map((d:any)=>[d.date,d.total])),em=new Map(expenses.map((d:any)=>[d.date,d.total]));
 const series=[];let cursor=new Date((monthly?from.slice(0,7)+'-01':from)+'T12:00:00Z');
 while(cursor.toISOString().slice(0,10)<=end){const key=cursor.toISOString().slice(0,monthly?7:10),day:any=dm.get(key)??{};series.push({date:key,name:cursor.toLocaleDateString('en-IN',monthly?{month:'short',year:'2-digit'}:range==='7'?{weekday:'short'}:{day:'numeric',month:'short'}),revenue:(day.revenue??0)/100,profit:((day.margin??0)-Number(lm.get(key)??0)-Number(em.get(key)??0))/100,bills:day.bills??0});monthly?cursor.setUTCMonth(cursor.getUTCMonth()+1):cursor.setUTCDate(cursor.getUTCDate()+1);}
 const report=await getReport(from,end);return response({...report,from,to:end,bucket:monthly?'month':'day',series,todayReport:(await getReport(end,end)).totals,stock:await one("SELECT COALESCE(SUM(qty*cost),0) value,COUNT(*) count FROM products WHERE kind='packaged' AND active=1")});
 }if(action==='report')return response(await getReport(u.searchParams.get('from')??today(),u.searchParams.get('to')??today(),qty(u.searchParams.get('offset')??0,true)));if(action==='bill'){const s=await one('SELECT * FROM sales WHERE id=?',u.searchParams.get('id'));if(!s)return response({error:'Bill not found.'},404);return response({...s,shop:JSON.parse(s.shop),lines:await all('SELECT * FROM lines WHERE sale=?',s.id)})}if(action==='movements'){const p=u.searchParams.get('product');return response(await all('SELECT m.*,p.name,p.variant FROM movements m JOIN products p ON p.id=m.product'+(p?' WHERE m.product=?':'')+' ORDER BY m.time DESC LIMIT 150',...(p?[p]:[])))}if(action==='expenses')return response(await all('SELECT * FROM expenses ORDER BY date DESC LIMIT 150'));if(action==='storage'){return response({sales:(await one('SELECT COUNT(*) n FROM sales')).n,lines:(await one('SELECT COUNT(*) n FROM lines')).n,movements:(await one('SELECT COUNT(*) n FROM movements')).n})}if(action==='export'){const from=date(u.searchParams.get('from')??today()),to=date(u.searchParams.get('to')??today());return response(await all('SELECT s.number,s.date,s.time,s.payment,s.status,l.name,l.brand,l.qty,l.price,l.qty*l.price total FROM sales s JOIN lines l ON l.sale=s.id WHERE s.date BETWEEN ? AND ? ORDER BY s.date,s.number',from,to))}return response({error:'Not found'},404)}catch(e:any){console.error(e);return response({error:'Could not load records. Please try again.'},503)}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&&origin!=='https://teammetacrash.github.io')return response({error:'Invalid request origin.'},403);if(Number(req.headers.get('content-length')??0)>100000)return response({error:'Request too large.'},413);const b:any=await req.json();if(!b||typeof b!=='object')return response({error:'Invalid request.'},400);const action=b.action;if(action==='login')return await login(req,b);if(!await authenticated(req))return response({error:'Please sign in.'},401);if(action==='logout'){await sql('DELETE FROM sessions WHERE token=?',await digest(cookie(req))).run();return response({ok:true},200,{'Set-Cookie':'jc_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0'})}if(action==='password'){const a=await one('SELECT * FROM admin WHERE id=1');if(!await verify(String(b.current??''),a.hash))throw new Error('Current password is incorrect.');if(typeof b.password!=='string'||b.password.length<12||b.password.length>200)throw new Error('Use a password of 12 to 200 characters.');await db().batch([sql('UPDATE admin SET hash=?,changed=1 WHERE id=1',await password(b.password)),sql('DELETE FROM sessions WHERE token<>?',await digest(cookie(req)))]);return response({ok:true})}const a=await one('SELECT changed FROM admin WHERE id=1');if(!a?.changed)return response({error:'Please change your temporary password first.'},403);
if(action==='product'){const id=b.id??crypto.randomUUID(),existing=b.id?await one('SELECT * FROM products WHERE id=?',b.id):null;if(b.id&&!existing)throw new Error('Item not found.');const kind=existing?.kind??b.kind;if(!['packaged','prepared'].includes(kind))throw new Error('Invalid item type.');const cat=await one('SELECT * FROM masters WHERE id=? AND kind=?',b.category,kind==='prepared'?'prepared':'category');if(!cat)throw new Error('Select a category.');if(kind==='packaged'&&!await one("SELECT id FROM masters WHERE id=? AND kind='brand'",b.brand))throw new Error('Select a brand.');const name=string(b.name),price=cents(b.price),variant=String(b.variant??'').slice(0,80),low=qty(b.low??5,true),active=b.active===false?0:1;if(existing){await sql('UPDATE products SET name=?,category=?,brand=?,variant=?,price=?,low=?,active=? WHERE id=?',name,b.category,kind==='packaged'?b.brand:null,variant,price,low,active,id).run()}else{const cost=kind==='packaged'?cents(b.cost):0,q=kind==='packaged'?qty(b.qty??0,true):0;const cmds=[sql('INSERT INTO products(id,name,kind,category,brand,variant,price,cost,qty,low,active) VALUES(?,?,?,?,?,?,?,?,?,?,?)',id,name,kind,b.category,kind==='packaged'?b.brand:null,variant,price,cost,q,low,active)];if(q)cmds.push(sql('INSERT INTO movements(id,product,date,time,type,qty,cost,note) VALUES(?,?,?,?,?,?,?,?)',crypto.randomUUID(),id,today(),now(),'opening',q,cost,'Opening stock'));await db().batch(cmds)}return response({ok:true,id})}
if(action==='master'){if(!['brand','category','prepared'].includes(b.kind))throw new Error('Invalid category type.');const name=string(b.name,60);if(b.id)await sql('UPDATE masters SET name=?,active=? WHERE id=? AND kind=?',name,b.active===false?0:1,b.id,b.kind).run();else await sql('INSERT INTO masters(id,kind,name,active) VALUES(?,?,?,1)',crypto.randomUUID(),b.kind,name).run();return response({ok:true})}
if(action==='stock'||action==='wastage'||action==='adjustment'){const p=await one("SELECT * FROM products WHERE id=? AND kind='packaged'",b.product);if(!p)throw new Error('Select a packaged item.');const d=eventDate(b.date),t=now(),id=string(b.key,80);if(await one('SELECT id FROM movements WHERE id=?',id))return response({ok:true});let q=qty(b.qty,action==='adjustment'),cost=action==='stock'?cents(b.cost):p.cost,note=string(b.note??'Stock received',250),delta=q;if(action==='wastage'){delta=-q;if(q>p.qty)throw new Error('Wastage cannot exceed available stock.')}if(action==='adjustment'){delta=q-p.qty;if(!delta)throw new Error('Physical count matches current stock.');}const update=action==='stock'?sql('UPDATE products SET cost=CASE WHEN qty+?>0 THEN (qty*cost+CAST(? AS double precision)*CAST(? AS double precision))/(qty+?) ELSE ? END,qty=qty+? WHERE id=?',q,q,cost,q,cost,q,p.id):sql('UPDATE products SET qty=qty+? WHERE id=?',delta,p.id);await db().batch([sql('INSERT INTO movements(id,product,date,time,type,qty,cost,note) VALUES(?,?,?,?,?,?,?,?)',id,p.id,d,t,action,delta,cost,note),update]);return response({ok:true})}
if(action==='sale'){const id=string(b.key,80);const old=await one('SELECT id FROM sales WHERE id=?',id);if(old)return response({ok:true,id});if(!Array.isArray(b.cart)||!b.cart.length||b.cart.length>100)throw new Error('Add at least one item to the bill.');if(!['Cash','UPI','Card','Other'].includes(b.payment))throw new Error('Select a payment method.');const map=new Map<string,number>();for(const l of b.cart)map.set(string(l.id),qty(l.qty)+(map.get(l.id)??0));const rows=[];let total=0,cost=0,packaged=0,prepared=0,units=0;for(const[id,q]of map){const p=await one('SELECT p.*,b.name brand_name,c.name category_name FROM products p LEFT JOIN masters b ON p.brand=b.id JOIN masters c ON p.category=c.id WHERE p.id=? AND p.active=1',id);if(!p)throw new Error('An item is no longer available. Refresh your bill.');if(p.kind==='packaged'&&q>p.qty)throw new Error(`${p.name}: only ${p.qty} left in stock.`);total+=p.price*q;units+=q;if(p.kind==='packaged'){cost+=p.cost*q;packaged+=p.price*q}else prepared+=p.price*q;rows.push({...p,q})}const d=eventDate(b.date??today()),t=now(),shop=await shopSettings();const commands=[sql("INSERT INTO sales(id,number,date,time,payment,total,cost,packaged,prepared,units,status,shop) VALUES(?,(SELECT COALESCE(MAX(number),0)+1 FROM sales),?,?,?,?,?,?,?,?,'completed',?)",id,d,t,b.payment,total,Math.round(cost),packaged,prepared,units,JSON.stringify(shop))];for(const p of rows){commands.push(sql('INSERT INTO lines(id,sale,product,name,brand,category,kind,price,cost,qty) VALUES(?,?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),id,p.id,p.name+(p.variant?' · '+p.variant:''),p.brand_name??'',p.category_name,p.kind,p.price,p.cost,p.q));if(p.kind==='packaged'){commands.push(sql('UPDATE products SET qty=qty-? WHERE id=?',p.q,p.id));commands.push(sql("INSERT INTO movements(id,product,date,time,type,qty,cost,note,sale) VALUES(?,?,?,?,'sale',?,?,'Sale',?)",crypto.randomUUID(),p.id,d,t,-p.q,p.cost,id))}}await db().batch(commands);return response({ok:true,id})}
if(action==='cancel'){const s=await one('SELECT * FROM sales WHERE id=?',b.id);if(!s)throw new Error('Bill not found.');if(s.status==='cancelled')return response({ok:true});const reason=string(b.reason,250),ls=await all("SELECT * FROM lines WHERE sale=? AND kind='packaged'",b.id),commands=[];for(const l of ls){commands.push(sql("UPDATE products SET cost=CASE WHEN qty+?>0 THEN (qty*cost+CAST(? AS double precision)*CAST(? AS double precision))/(qty+?) ELSE cost END,qty=qty+? WHERE id=? AND EXISTS(SELECT 1 FROM sales WHERE id=? AND status='completed')",l.qty,l.qty,l.cost,l.qty,l.qty,l.product,s.id));commands.push(sql("INSERT INTO movements(id,product,date,time,type,qty,cost,note,sale) SELECT ?,?,?,?,'cancellation',?,?,?,? WHERE EXISTS(SELECT 1 FROM sales WHERE id=? AND status='completed')",crypto.randomUUID(),l.product,today(),now(),l.qty,l.cost,reason,s.id,s.id))}commands.push(sql("UPDATE sales SET status='cancelled',reason=? WHERE id=? AND status='completed'",reason,s.id));await db().batch(commands);return response({ok:true})}
if(action==='expense'){const id=string(b.key,80);await sql('INSERT OR IGNORE INTO expenses(id,date,category,amount,note) VALUES(?,?,?,?,?)',id,eventDate(b.date),string(b.category,60),cents(b.amount),String(b.note??'').slice(0,250)).run();return response({ok:true})}
if(action==='settings'){await sql('UPDATE settings SET name=?,phone=?,address=?,footer=? WHERE id=1',string(b.name,80),String(b.phone??'').slice(0,30),String(b.address??'').slice(0,250),String(b.footer??'').slice(0,150)).run();return response({ok:true})}
return response({error:'Unknown action.'},400)}catch(e:any){console.error(e);let message=e.message??'Could not save. Please try again.';if(e.code==='23505'||message.includes('UNIQUE'))message='This record already exists. Refresh and try again.';if(message.includes('nonnegative_stock'))message='Stock changed while billing. Refresh and check the available quantity.';if(e.code||message.includes('D1_')||message.includes('SQLITE_'))message='Could not save this entry. Please refresh and try again.';return response({error:message},400)}}
