import { AsyncLocalStorage } from "node:async_hooks";
export const context=new AsyncLocalStorage<any>();
export function sql(q:string,...args:any[]){
 let n=0;let statement=q.replace(/\?/g,()=>'$'+(++n));
 if(statement.startsWith('INSERT OR IGNORE'))statement=statement.replace('INSERT OR IGNORE','INSERT')+' ON CONFLICT DO NOTHING';
 const run=()=>context.getStore().unsafe(statement,args);
 return{run,all:async()=>({results:await run()}),first:async()=>(await run())[0]??null};
}
export function db(){return{batch:async(commands:any[])=>{for(const cmd of commands)await cmd.run()}}}
export async function all(q:string,...args:any[]){return(await sql(q,...args).all()).results}
export async function one(q:string,...args:any[]){return await sql(q,...args).first()}
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const now=()=>new Date().toISOString();
export function string(v:any,max=120){if(typeof v!=='string'||!v.trim()||v.trim().length>max)throw new Error('Please fill all required fields correctly.');return v.trim()}
export function qty(v:any,zero=false){const n=Number(v);if(!Number.isInteger(n)||n<(zero?0:1)||n>1000000)throw new Error('Enter a valid whole-number quantity.');return n}
export function cents(v:any){const n=Number(v);if(v===''||!Number.isFinite(n)||n<0||n>1000000)throw new Error('Enter a valid non-negative price.');return Math.round(n*100)}
export function date(v:any){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||new Date(v+'T12:00:00Z').toISOString().slice(0,10)!==v)throw new Error('Choose a valid date.');return v}
export function eventDate(v:any){const d=date(v);if(d>today())throw new Error('Future dates are not allowed.');return d}
export async function digest(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,'0')).join('')}
export async function password(p:string,salt?:string){salt=salt??crypto.randomUUID();const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:new TextEncoder().encode(salt),iterations:100000},key,256);return salt+':'+Array.from(new Uint8Array(bits),b=>b.toString(16).padStart(2,'0')).join('')}
export async function verify(p:string,hash:string){const guess=await password(p,hash.split(':')[0]);let diff=guess.length^hash.length;for(let i=0;i<hash.length;i++)diff|=hash.charCodeAt(i)^(guess.charCodeAt(i)||0);return diff===0}
export function cookie(req:Request){return req.headers.get('x-shop-session')??''}
export async function authenticated(req:Request){const token=cookie(req);if(!token)return false;const hash=await digest(token);const session=await one('SELECT * FROM sessions WHERE token=? AND expires>?',hash,Date.now());if(!session)return false;await sql('UPDATE sessions SET expires=? WHERE token=?',Date.now()+7200000,hash).run();return true}
export function response(data:any,status=200,headers:Record<string,string>={}){return Response.json(data,{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}})}
export async function init(){await sql("INSERT OR IGNORE INTO settings(id,name,phone,address,footer) VALUES(1,'JUICE CRAFT','','','Thank you for visiting. Crafted with care, served with love.')").run();const seeds=[['brand','Arun'],['brand','Dairy Day'],['category','Popsicles'],['category','Cups'],['category','Cones'],['category','Family Packs'],['category','Bulk'],['prepared','Mojito'],['prepared','Sharjah'],['prepared','Juice'],['prepared','Milkshake'],['prepared','Falooda']];await db().batch(seeds.map(([kind,name])=>sql('INSERT OR IGNORE INTO masters(id,kind,name) VALUES(?,?,?)',kind+'-'+name.toLowerCase().replaceAll(' ','-'),kind,name)))}
export async function shopSettings(){return await one('SELECT * FROM settings WHERE id=1')}
export async function login(req:Request,b:any){const ip=await digest((req.headers.get('x-forwarded-for')??'unknown').split(',')[0].trim());await sql('DELETE FROM attempts WHERE until<?',Date.now()).run();await sql('DELETE FROM sessions WHERE expires<?',Date.now()).run();await sql('INSERT INTO attempts(key,count,until) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=attempts.count+1',ip,Date.now()+900000).run();const attempt=await one('SELECT count FROM attempts WHERE key=?',ip);if(attempt.count>10)return response({error:'Too many attempts. Please wait 15 minutes.'},429);let a=await one('SELECT * FROM admin WHERE id=1');const initial=undefined;if(!a&&!initial)return response({error:'Admin access is not configured yet.'},503);const hash=a?.hash??initial;const ok=await verify(String(b.password??''),hash);if(b.username!=='admin'||!ok)return response({error:'Username or password is incorrect.'},401);if(!a){await sql('INSERT OR IGNORE INTO admin(id,hash,changed) VALUES(1,?,0)',hash).run();a=await one('SELECT * FROM admin WHERE id=1');}await init();await sql('DELETE FROM attempts WHERE key=?',ip).run();const token=crypto.randomUUID()+crypto.randomUUID();await sql('INSERT INTO sessions(token,expires) VALUES(?,?)',await digest(token),Date.now()+7200000).run();return response({ok:true,mustChange:!a.changed,session:token})}
export async function getReport(from:string,to:string,offset=0){date(from);date(to);if(from>to)throw new Error('Start date must be before the end date.');const totals=await one("SELECT COALESCE(SUM(total),0) revenue, COALESCE(SUM(packaged-cost),0) margin, COALESCE(SUM(prepared),0) prepared,COALESCE(SUM(units),0) units,COUNT(*) bills FROM sales WHERE date BETWEEN ? AND ? AND status='completed'",from,to);const waste=await one("SELECT COALESCE(SUM(-qty*cost),0) total FROM movements WHERE type IN ('wastage','adjustment') AND qty<0 AND date BETWEEN ? AND ?",from,to);const exp=await one('SELECT COALESCE(SUM(amount),0) total FROM expenses WHERE date BETWEEN ? AND ?',from,to);return {totals:{...totals,waste:Math.round(waste.total),expenses:exp.total,net:Math.round(totals.margin-waste.total-exp.total)},sales:await all('SELECT * FROM sales WHERE date BETWEEN ? AND ? ORDER BY date DESC,time DESC LIMIT 50 OFFSET ?',from,to,offset),count:(await one('SELECT COUNT(*) n FROM sales WHERE date BETWEEN ? AND ?',from,to)).n,items:await all("SELECT l.name,l.brand,l.category,SUM(l.qty) qty,SUM(l.qty*l.price) revenue FROM lines l JOIN sales s ON s.id=l.sale WHERE s.date BETWEEN ? AND ? AND s.status='completed' GROUP BY l.product,l.name,l.brand,l.category ORDER BY revenue DESC LIMIT 100",from,to),payments:await all("SELECT payment,SUM(total) total FROM sales WHERE date BETWEEN ? AND ? AND status='completed' GROUP BY payment",from,to)}}
